version = "1.0"

[metadata]
tags = ["datagen-flash", "model_training"]

[verifier]
timeout_sec = 900.0

[agent]
timeout_sec = 900.0

[environment]
build_timeout_sec = 600.0
cpus = 5
memory = "8G"
docker_image = "gitlab-master.nvidia.com:5005/renjiep/datagen-flash-images/hb__datagen-flash-data-science:latest"
