version = "1.0"

[metadata]
tags = ["datagen-flash", "debugging"]

[verifier]
timeout_sec = 900.0

[agent]
timeout_sec = 900.0

[environment]
build_timeout_sec = 600.0
cpus = 1
memory = "2G"
docker_image = "gitlab-master.nvidia.com:5005/renjiep/datagen-flash-images/hb__datagen-flash-debugging:latest"
