lockfileVersion: '9.0'

importers:

  .:
    configDependencies: {}
    packageManagerDependencies:
      '@pnpm/exe':
        specifier: ^11.7.0
        version: 11.9.0
      pnpm:
        specifier: ^11.7.0
        version: 11.9.0

packages:

  '@pnpm/exe@11.9.0':
    resolution: {integrity: sha512-pPPOpR79qW3nsNhlyDIdfstli4Bi78mk8r22ySxpFRwMbO8KXSjGrVzGmJBsVX39NnJTh7/WADj527nZhG9H9g==}
    hasBin: true

  '@pnpm/linux-x64@11.9.0':
    resolution: {integrity: sha512-fl7W5imnSmmgXIqMQFZ/rPaVvk9OkKF8/anqHZE3XEDfWcn3BlWGndyOEas/JN7u2BXWYjs63DJZ3rnG6WOhLA==}
    cpu: [x64]
    os: [linux]

  '@reflink/reflink@0.1.19':
    resolution: {integrity: sha512-DmCG8GzysnCZ15bres3N5AHCmwBwYgp0As6xjhQ47rAUTUXxJiK+lLUxaGsX3hd/30qUpVElh05PbGuxRPgJwA==}
    engines: {node: '>= 10'}

  detect-libc@2.1.2:
    resolution: {integrity: sha512-Btj2BOOO83o3WyH59e8MgXsxEQVcarkUOpEYrubB0urwnN10yQ364rsiByU11nZlqWYZm05i/of7io4mzihBtQ==}
    engines: {node: '>=8'}

  pnpm@11.9.0:
    resolution: {integrity: sha512-vWgtXQP+Ul73yf1ngMaITR51asTJyf4AxTh4KCQxDc+Q493E9Tg18G3669UIXkGFXgvLs7YN4qxburieUDbwOw==}
    engines: {node: '>=22.13'}
    hasBin: true

snapshots:

  '@pnpm/exe@11.9.0':
    dependencies:
      '@reflink/reflink': 0.1.19
      detect-libc: 2.1.2
    optionalDependencies:
      '@pnpm/linux-x64': 11.9.0

  '@pnpm/linux-x64@11.9.0':
    optional: true

  '@reflink/reflink@0.1.19': {}

  detect-libc@2.1.2: {}

  pnpm@11.9.0: {}

---
lockfileVersion: '9.0'

settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

importers:

  .:
    dependencies:
      left-pad:
        specifier: 2.3.1
        version: 2.3.1

packages:

  left-pad@2.3.1:
    resolution: {integrity: sha512-N5zU0m7XVqBH9CLVhD8BTbSVyWmAElRYyl0w0HX9llV9GSE/Q0eEtAOE4JUJpUZ6eWqG6XLYR7RwZKEqLcA6bA6==}
    engines: {node: '>=0.10.0'}

snapshots:

  left-pad@2.3.1: {}